### ISSUE TITLE
missing `organisation` parameter for some api calls

### ISSUE THREAD

**Issue by mikomraz** [shijl-0925/python-sonarqube-api#6]
Hello @shijl-0925 👋 

Thank you for the great work! It is a handy python library to deal with Sonar's api.

I would like to raise an issue I noticed: for some api, there the field `organisation` is required, and there is no way to pass it.
For example:
https://sonarcloud.io/web_api/api/rules/tags?query=rules

`GET api/rules/tags`
```
>>> list(sonar.rules.get_rule(rule_key=rule))
sonarqube.exceptions.ValidationError: Error in request. Possibly validation error [400]: The 'organization' parameter is missing
```

and some, even though documentation says "optional" it is still needed, like in `GET api/rules/search`:
```
>>> list(sonar.rules.search_rules(q=rule))
sonarqube.exceptions.ValidationError: Error in request. Possibly validation error [400]: The 'organization' parameter is missing
```

Besides adding the missing parameters, maybe it's possible to allow extra ones? or add `organization` as part of session?

Thank you very much!

**Comment by shijl-0925** [comment]
python-sonarqube-api >=1.1.3 support SonarCloud APIs. please use The latest installation package。

from sonarqube import SonarCloudClient
h = SonarCloudClient(sonarcloud_url="https://sonarcloud.io", token='*****************')
